@base=http://0.0.0.0:3000

### @name get account

GET {{base}}/v1/accounts/1 HTTP/1.1

### create account

POST {{base}}/v1/accounts HTTP/1.1
Content-Type: application/json

{
  "document_number": "1234567809"
}
